version: "3.3"
networks:
  dev:
    name: dev
services:
  server:
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT}
        reservations:
          memory: ${MEMORY_RESERVATIONS}
    image: cosmos:dev
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command:
      - /bin/bash
      - -c
      - |
        tail -f /dev/null
    volumes:
      - .:/app
      - ./.starport:/root/.starport
    # environment:
    #   - CONCURRENT
    ports:
    #   - ${SERVER_PORT}:${SERVER_PORT}
      - 12345-12350:12345-12350
      - 8080:8080
      - 26657-26660:26657-26660
      - 1317-1318:1317-1318
    networks:
      - dev
    restart: always
